### PR TITLE
Apple clone 

### PR DESCRIPTION
**Pull request by imhilla**
This is a project about embedding images, using gradients and to style the nav.

### CODE REVIEW

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @imhilla 👋

Your project looks awesome, but for a few needed adjustments.👌👌

Kindly fix this issues:👇

- [ ] Required - Kindly enable stickler on your repo and fix the linting errors, discovered.

- [ ] REQUIRED - PLEASE TAKE NOTE OF THIS: In future projects DO NOT make commits directly to the master branch, all commits should be made in a different branch, kindly AVOID committing to the master branch directly. Ensure you follow the GitHub Flow guidelines as stated in this [link](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/)

- [ ] Required - Also ensure you validate your HTML code with this HTML5 validator [tool](https://validator.w3.org/nu/#file) and fix the errors there.

- [ ] Also ensure the search input field at the navbar is actually a search input field as expected.
ice_screenshot_20200408-132116

- [ ] Required - In addition, adjust the bottom image elements they seem to be overflowing the width of the page.
ice_screenshot_20200408-125716

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by sumancrest0001** [comment]
### STATUS: CHANGES REQUIRED

Hello @imhilla  
Nice work and everything looks perfect to me. BUT we need to tick one requirement for this project.
We need to use two techniques from **flex, float, and grid** to layout our project. Please have a look at the [requirement](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/).Currently, you are using only **float**.  I know it's a minor thing but we have to tick every small requirement and it's a good practice.  
**Please submit for another review after fixing this issue.**
:+1: :+1:

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @imhilla !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

- [ ] seems that you added the input here but is out of the box could you fix it please?
Screenshot_2020-04-08 Apple

- [ ] in wide screens the pre-footer section should be aligned with the main image, kindly fix this. 
Screenshot_2020-04-08 Apple(1)

- [ ]  flex is not used properly since is only one child in the footer div, you could use flexbox in the UL where you keep the images instead, you should take a look on [this  guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is a complete resource where you can learn how to use flexbox. 

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :1st_place_medal: 

Hi @imhilla :smile_cat:  :smile_cat:
You have been doing a hard work and your page looks beautiful and professional, congrats for that :1st_place_medal: :1st_place_medal: 

### **Your project were approved** :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: 

:bulb: :bulb: **No need to submit for another review but before you merge it into master, can you please update the live version to show a hyperlink?** 
**In your readme it is showing a link. The way to do it is just as the usual** `<a href="">Live version</a>`

_SUGGESTION FOR THE NEXT PROJECTS:_

:v: On every pull request, it is required to add a short summary that describes what you did on the project or what you fixed after the review and before the submissions for another review. Can you please consider it on the next pull requests? :smile_cat: 

:v: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''apple-page'' instead of ''feature', for example. It will be more descriptive. :muscle: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

### **Project reviewed by Thaís Vieira (TSE)**

**Pull request merged**
